spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/yacht_score
spring.datasource.username=postgres
spring.datasource.password=Pkousaku315@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
